$office_apps = ^(Microsoft (Word|Excel|PowerPoint|Publisher|Powershell|Visual Studio))$

windowrule {  
    name  = suppress-office-maximize 
    match:class = $office_apps  
    suppress_event = maximize  
}
